#!/usr/bin/env python

import os,sys,time,psutil,redis
from model import Model


# 
def run(ip, number):
	model = Model(ip)
	res = model.getQuery(number)
	if res :
		model.getData()
		model.process()

if __name__ == "__main__":
	ip = sys.argv[1]
	number = sys.argv[2]
	run(ip, number)
