#-------------------------------------------------------------------------
#
# Makefile--
#    Makefile for utils/model
#
# IDENTIFICATION
#    src/backend/utils/model/Makefile
#
#-------------------------------------------------------------------------

subdir = src/backend/utils/model
top_builddir = ../../../..
include $(top_builddir)/src/Makefile.global

OBJS = \
	model.o

include $(top_srcdir)/src/backend/common.mk
